### ISSUE TITLE
CONCURRENCY_PAGE with headless: false hangs up and breaks

### ISSUE THREAD

**Issue by VikramTiwari** [thomasdondorf/puppeteer-cluster#52] opened 2018-11-01 23:08 UTC
```
const { Cluster } = require('../dist');

(async () => {
    // Create a cluster with 2 workers
    const cluster = await Cluster.launch({
        concurrency: Cluster.CONCURRENCY_PAGE,
        maxConcurrency: 2,
        puppeteerOptions: {headless: false}
    });

    // Define a task (in this case: screenshot of page)
    await cluster.task(async ({ page, data: url }) => {
        await page.goto(url);

        const path = url.replace(/[^a-zA-Z]/g, '_') + '.png';
        await page.screenshot({ path });
        console.log(`Screenshot of ${url} saved: ${path}`);
    });

    // Add some pages to queue
    await cluster.queue('https://www.google.com');
    await cluster.queue('https://www.wikipedia.org');
    await cluster.queue('https://github.com/');

    // Shutdown after everything is done
    await cluster.idle();
    await cluster.close();
})();
```

This only generated screenshots for wiki and github. Browser also hung for some time.

**Comment by thomasdondorf** [comment] 2018-11-02 09:44
I cannot reproduce the problem. Could you provide some details about your system? The browser just stopped working and then continued after some time (maybe 30s as this is the default timeout)?

The fix you provided closes the page at the end of the task. This is already [handled by the library](https://github.com/thomasdondorf/puppeteer-cluster/blob/master/src/browser/ConcurrencyPage.ts#L74). Does it actually solve the problem?

**Comment by thomasdondorf** [comment] 2018-11-05 19:11
I'm unable to reproduce the problem. Can you provide more information? What hangs? The screenshots are saved and then the page does not close after the `page.screenshot(..)` call? Or is it maybe the `page.goto(..)` that hangs?

**Comment by thomasdondorf** [comment] 2018-12-21 15:03
Closing this for now. Feel free to reopen in case you think this library is actually the issue.

**Closed by thomasdondorf** 2018-12-21 15:03 UTC
